### PR TITLE
fix Position Independent Executable (PIE) handling

### LINKED ISSUE #605: Handling of PIE binaries
On recent Linux distributions, the system compiler will by default generate position independent executables (PIEs). Dyninst currently has at least two issues when dealing with PIE:

1. A few interface checks whether a binary is a shared library. Such check will wrongly return that PIEs are shared libraries. The boundary between shared library and PIE is indeed blur. We need to come up with a reliable way to distinguish PIE from shared libraries.

2. Static PIE was not legal until recently. To generate static PIE, flag "-static-pie" should be used rather than two flags "-static" and "-fie". Dyninst currently cannot correctly identify static PIE as static binary. Static pie contains necessary dynamic information for relocation, so Dyninst treats static PIE as dynamically linked. This will be the first step towards correctly instrumenting static PIE.

### PR DESCRIPTION
**Pull request by kupsch**
All functions that determine if an object is a shared library and/or an
executable are now based on a single set of functions in Object-elf.
This make all the functions in the various Dyninst libraries and classes
consistent and also makes Dyninst correctly handle PIE executables.
These functions in Object-elf are based on functions found in elfutils's
elfclassify program (with small improvements to better determine if a
shared library is also an executable).   The new functions in Object-elf
include:

    * isOnlyExecutable()
    * isExecutable()
    * isSharedLibrary()
    * isOnlySharedLibrary()
    * isLoadable()
    * isDebugOnly()
    * isLinuxKernelModule()

Symtab exposes some of these functions through its public API.  isExec()
now correctly handles PIE executables, and two new functions were added
to determine if the underlying file is a shared library, an executable,
or both.  These function are:

    * isExec()            (isExecutable() and not isSharedLibrary())
    * isExecutable()
    * isSharedLibrary()

Fixes #605

### CODE REVIEW

**Comment by kupsch** [comment]
This passes on both coriander and zeroah.  This should be tested with the current testsuite and the current testsuite with commit d2d3aba2 reverted so PIE executables are tested (assuming the compiler/linker default to generating PIE).

File: dyninstAPI/src/image.h [hunk 1]
```diff
@@ -361,8 +356,9 @@ class image : public codeRange {
    ParseAPI::CodeObject *codeObject() const { return obj_; }
 
    bool isDyninstRTLib() const { return is_libdyninstRT; }
-   bool isAOut() const { return is_a_out; }
-   bool isSharedObj() const { 
+   bool isExecutable() const { return getObject()->isExec(); }
+   bool isSharedLibrary() const { return getObject()->isSharedLibrary(); }
+   bool isSharedObject() const {
```
Comment (hainest) [inline dyninstAPI/src/image.h:361]: What's the difference between `isSharedLibrary` and `isSharedObject`?

File: symtabAPI/h/Symtab.h [hunk 2]
```diff
@@ -235,6 +235,8 @@ class SYMTAB_EXPORT Symtab : public LookupInterface,
 
    /*****Query Functions*****/
    bool isExec() const;
+   bool isExecutable() const;
+   bool isSharedLibrary() const;
```
Comment (hainest) [inline symtabAPI/h/Symtab.h:239]: Hmm... This is an API break. I know we discussed this before, but what was our rationale for removing these?

File: symtabAPI/src/Symtab.C [hunk 3]
```diff
@@ -373,9 +373,20 @@ SYMTAB_EXPORT Symtab::Symtab() :
 
 SYMTAB_EXPORT bool Symtab::isExec() const 
 {
+    assert( is_a_out == obj_private->isOnlyExecutable() );
```
Comment (hainest) [inline symtabAPI/src/Symtab.C:376]: If this is a class invariant, we should enforce it in the constructor.

**Review by hainest — CHANGES_REQUESTED** [review]

**Comment by hainest** [comment]
@kupsch Could you submit a PR to revert d2d3aba2 in the testsuite?

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1042

Runs without PIE binaries in the test suite look good.

File: dyninstAPI/src/image.h (hunk 1 above)
Comment (kupsch) [reply dyninstAPI/src/image.h:361]: isSharedObject is elf type if DYN.  It is only used to determine a startup_printf message.   renamed old function (was isSharedObj).

isSharedLibrary besides the elf type being DYN has to meet all the other requirement of being a shared library as determined by the Object class.

File: symtabAPI/h/Symtab.h (hunk 2 above)
Comment (kupsch) [reply symtabAPI/h/Symtab.h:239]: These are added methods.  Adding two non-virtual functions shouldn't be an API or ABI break.

File: symtabAPI/src/Symtab.C (hunk 3 above)
Comment (kupsch) [reply symtabAPI/src/Symtab.C]: I will remove.  Present from early validation testing of the old and new code and I forgot to remove this.

File: symtabAPI/h/Symtab.h (hunk 2 above)
Comment (hainest) [reply symtabAPI/h/Symtab.h:239]: Wow. I must be going color blind because I thought those were red...

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1042&testsuite_branch=PR188

And runs with PIE enabled are good. Nice!
