### PR TITLE
proccontrol: Handle "ghost" threads

### LINKED ISSUE #741: proccontrol hangs manifesting in test_thread_X
## ARM
`test_thread_5` is intermittently hanging on Zeroah. The most common case where the hang is seen is `test_thread_5 g++ dynamiclink create pic`. I've not seen any hangs or crashes on arm1.cs.rice.edu. I've [skipped](https://github.com/dyninst/testsuite/pull/131) this test for now, and the test suite is now running to [completion](https://bottle.cs.wisc.edu/details/306). `pc_irpc gcc dynamiclink attach nonpic` hanged on Zeroah just once- a variant of which has crashed on [Power9](https://bottle.cs.wisc.edu/results/CRASHED/295).

## x86
`test_thread_{1,3,8}` is intermittently failing on x86.

On coriander, [260](https://bottle.cs.wisc.edu/details/260) failed on `test_thread_1`, but just re-running passes ([265](https://bottle.cs.wisc.edu/details/265)). [269](https://bottle.cs.wisc.edu/results/CRASHED/269) crashes on `test_thread_8`; running master (which contains this PR) passes ([274](https://bottle.cs.wisc.edu/details/274)).

On GalacticCentralPoint, [261](https://bottle.cs.wisc.edu/details/261) crashes on `test_thread_3`, but running on master (which contains this PR) passes ([271](https://bottle.cs.wisc.edu/details/271)). Another is [303](https://bottle.cs.wisc.edu/details/303) and just rerunning passes ([304](https://bottle.cs.wisc.edu/details/304)).

The most common error seen in the logs is SIGSEGV.

## Power
Power8 appears to be impervious, but Power9 has seen one failure ([295](https://bottle.cs.wisc.edu/details/295)) where re-running succeeds ([298](https://bottle.cs.wisc.edu/details/298)).

Power 9 on llnl.cs.rice.edu had two failures on [307](https://bottle.cs.wisc.edu/results/FAILED/307), but passed when run again ([314](https://bottle.cs.wisc.edu/details/314)).

### PR DESCRIPTION
**Pull request by hainest**
Fixes #741

A "ghost" thread is one which has encountered an error when continuing
from a SIGSTOP. This can come about from the process being exited before
the SIGSTOP is handled.

@sashanicolas @mplegendre

### CODE REVIEW

File: proccontrol/src/linux.C [hunk 1]
```diff
@@ -2830,6 +2830,22 @@ bool linux_thread::plat_setRegisterAsync(Dyninst::MachRegister reg,
...
+	struct stat dummy;
+	int res = stat(loc.c_str(), &dummy);
+
+	pthrd_printf("GHOST_THREAD: exists=%d, loc=%s\n", res, loc.c_str());
+
+	if(res == -1) {
+		EventLWPDestroy::ptr lwp_ev = EventLWPDestroy::ptr(new EventLWPDestroy(EventType::Post));
+		lwp_ev->setSyncType(Event::async);
+		lwp_ev->setThread(thread());
+		dynamic_cast<linux_process*>(proc()->llproc())->decodeTdbLWPExit(lwp_ev);
```
Comment (hainest) [inline proccontrol/src/linux.C:2844]: When running, I am seeing the error

    test_driver: /home/tim/workspace/spack/opt/spack/linux-linuxmint18-piledriver/gcc-8.3.0/boost-1.70.0-6hhwr4jmmv5a52i3wqavu6kc4xnslczo/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = const Dyninst::ProcControlAPI::Process; typename boost::detail::sp_member_access<T>::type = const Dyninst::ProcControlAPI::Process*]: Assertion `px != 0' failed.

I believe it's this line that is causing it. I'm not sure if it's `proc` or `llproc` that is the underlying issue.

Comment (mplegendre) [reply proccontrol/src/linux.C:2844]: I'm not immediately sure why this line would crash--the process containing a linux_thread is almost certainly a linux_process.  

It could be simplified to just call llproc() instead of proc()->llproc().  int_thread has a routine that returns its int_process.  But that shouldn't make a behavior difference.

Can you get in there with a debugger and see more precisely  what exactly is failing?

Could you get in there with a debugger

Comment (hainest) [reply proccontrol/src/linux.C:2844]: >It could be simplified to just call llproc() instead of proc()->llproc().

Ah, ok. I was poking around in the types to get it to compile.

>Can you get in there with a debugger and see more precisely what exactly is failing?

That was my next step. I'll let you know what I find.

Comment (hainest) [reply proccontrol/src/linux.C:2844]: I've finally found a reproducer, but gdb can't create a stacktrace because `test_driver` has exited normally.

@sashanicolas  @mxz297 Is there a way to run the test directly under gdb with a particular threading model (I need the MPMT version as it's the only one that consistently crashes).

    $ gdb --args ./runTests -64 -g++ -none -create -dynamiclink -nonpic -test pc_fork -log tmp.log -all

    >set env ...
    >run

    Starting program: /home/tim/paradyn/kcr4_5A6/testsuite/tests/runTests -64 -g++ -none -create -dynamiclink -nonpic -test pc_fork -log tmp.log -all
    [Detaching after fork from child process 3345]
    [Detaching after fork from child process 3347]
    [Detaching after fork from child process 3354]
    pc_fork                    g++    none 64  create   SPST    dynamic nonPIC  PASSED
    pc_fork                    g++    none 64  create   MPST    dynamic nonPIC  PASSED
    test_driver: /home/tim/workspace/spack/opt/spack/linux-linuxmint18-piledriver/gcc-8.3.0/boost-1.70.0-6hhwr4jmmv5a52i3wqavu6kc4xnslczo/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = const Dyninst::ProcControlAPI::Process; typename boost::detail::sp_member_access<T>::type = const Dyninst::ProcControlAPI::Process*]: Assertion `px != 0' failed.
    *** Child terminated abnormally via signal 6.
    [Detaching after fork from child process 3447]
    pc_fork                    g++    none 64  create   SPMT    dynamic nonPIC  CRASHED (Running Test)
    test_driver: /home/tim/workspace/spack/opt/spack/linux-linuxmint18-piledriver/gcc-8.3.0/boost-1.70.0-6hhwr4jmmv5a52i3wqavu6kc4xnslczo/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = const Dyninst::ProcControlAPI::Process; typename boost::detail::sp_member_access<T>::type = const Dyninst::ProcControlAPI::Process*]: Assertion `px != 0' failed.
    Child received unexpected signal: 5
    *** Child terminated abnormally via signal 6.
    [Detaching after fork from child process 3620]
    pc_fork                    g++    none 64  create   MPMT    dynamic nonPIC  CRASHED (Running Test)
    [Inferior 1 (process 3341) exited normally]
    (gdb) bt
    No stack.

Comment (mxz297) [reply proccontrol/src/linux.C:2844]: @hainest You can just replace `runTests` with `test_driver` in your gdb command line.

Comment (hainest) [reply proccontrol/src/linux.C:2844]: For some reason, the file uploader here isn't working, so I've put the log on my google drive (https://drive.google.com/open?id=1KAUjjA_uZm1rLZOeCiOuawX4g9pBFvax).

When we pull the message out of the [mailbox](https://github.com/dyninst/dyninst/blob/master/proccontrol/src/process.C#L1096), the shared pointer has been either fully destroyed or never assigned a value.

Comment (hainest) [reply proccontrol/src/linux.C:2844]: I stepped through the messages, and the bad message is

    Thread 2 "test_driver" hit Breakpoint 1, int_process::waitAndHandleEvents (block=<optimized out>)
        at /home/tim/paradyn/kcr4_5A6/dyninst/src/proccontrol/src/process.C:1057
    1057        Event::ptr ev = mbox()->dequeue(should_block);
    (gdb) p ev
    $45 = {px = 0x0, pn = {pi_ = 0x7ffff339ce42 <__GI___pthread_mutex_lock+258>}}

What kind of message has a pthread mutex as its payload?

**Comment by hainest** [comment]
@mplegendre Our fix of adding `setProcess(proc())` fixed the previous issue, so I'm starting a new thread here. We're now getting a segfault here:

    Thread 1 "test_driver" received signal SIGSEGV, Segmentation fault.
    HandleThreadDestroy::handleEvent (this=<optimized out>, ev=...) at /home/tim/paradyn/3RuoMtOf/dyninst/src/proccontrol/src/handler.C:988
    988   if (!thrd->isUser()) {

It looks like the internal thread isn't present when handling our created ThreadDestroy event. I tried to put a conditional breakpoint there to get a better stack trace, but I haven't been able to figure out how to make gdb return control of the program to me at that point in the thread that hit the breakpoint. I need to read up on using gdb in multithreaded applications.

**Comment by hainest** [comment]
@mplegendre @sashanicolas @mxz297 

I've run into an issue with test_thread_7 where it only (but consistently) crashes when run under `runTests`, but not under `test_driver`. This has made debugging essentially impossible. The error message is

    test_driver: /home/tim/paradyn/mB_HCuuB/dyninst/src/proccontrol/src/process.C:4590: void int_threadPool::rmThread(int_thread*): Assertion `thrd != initial_thread' failed.
    *** Child terminated abnormally via signal 6.

Any thoughts?

**Comment by mplegendre** [comment]
The initial_thread is the thread that started main().  It's asserting that this thread isn't a thread destroy event, as it should be a process destroy.  

The ghost thread must be triggering for the main thread.  We shouldn't create thread destroy events for this case.

It would also be a good idea to investigate these extra triggers of the ghost thread code.  What's happening in these cases?  For a rare aarch64 race, we're triggering the test for it fairly often.  We may be creating premature thread destroy events.

**Comment by hainest** [comment]
@mplegendre 

Is this check sufficient/correct to avoid this situation?

    diff --git a/proccontrol/src/linux.C b/proccontrol/src/linux.C
    index a9a8aba..9118d1a 100644
    --- a/proccontrol/src/linux.C
    +++ b/proccontrol/src/linux.C
    @@ -2837,7 +2837,13 @@ void linux_thread::plat_handle_ghost_thread() {
     
            pthrd_printf("GHOST_THREAD: exists=%d, loc=%s\n", res, loc.c_str());
     
    -       if(res == -1) {
    +       // If the thread is still active, do nothing
    +       if(res != -1) return;
    +
    +       auto *initial_thread = llproc()->threadpool->initialThread();
    +
    +       // Do not create a destroy event for the thread executed from 'main'
    +       if(initial_thread != thread()->llthrd()) {
                    EventLWPDestroy::ptr lwp_ev = EventLWPDestroy::ptr(new EventLWPDestroy(EventType::Post));
                    lwp_ev->setSyncType(Event::async);
                    lwp_ev->setThread(thread());

**Comment by mplegendre** [comment]
I think that would work.

**Comment by hainest** [comment]
@mplegendre 

I finally got a hang to happen often enough on our local ARM machine, zeroah.cs.wisc.edu, to record some debug information. [test_thread_6.zeroah.hanged.log](https://github.com/dyninst/dyninst/files/4674844/test_thread_6.zeroah.hanged.log)

There is also a variant of test_thread_6 that is always failing because one of its threads is dying before the test suite is ready to terminate, and so it thinks it is missing a thread. I don't know if this is the same issue as our ghost threads, but it's another data point. [test_thread_6.zeroah.failed.log](https://github.com/dyninst/dyninst/files/4674849/test_thread_6.zeroah.failed.log)

**Comment by hainest** [comment]
@mplegendre Did you have a chance to look over the latest logs from the hanged tests?

**Comment by mplegendre** [comment]
That looks like an issues reading thread_db information.  You can debug that in the int_thread_db.C file, and documentation for the thread_db interface is online.
