### PR TITLE
Fix compile warnings for AMDGPU for Release 11.0

### LINKED ISSUE #952: Compiler warnings for AMD GPU code
@bbiiggppiigg

The -Wreorder -Wswitch warnings we definitely want to get fixed before the 11.0 release.

**-Wreorder**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:262
	‘Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isModifyPC’ will be initialized after 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:248
		‘bool Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isSMEM’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:70
		when initialized here 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:256
	‘Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isCall’ will be initialized after 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:241
		‘unsigned int Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::immLen’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:70
		when initialized here 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:256
	‘Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isCall’ will be initialized after 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:241
		‘unsigned int Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::immLen’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:70
		when initialized here 

**-Wswitch**
dyninst/src/common/src/dyn_regs.C:208
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

dyninst/src/common/src/dyn_regs.C:380
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

dyninst/src/common/src/dyn_regs.C:407
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

dyninst/src/parseAPI/src/SymbolicExpression.C:369
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

**-Wtype-limits**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:588
	comparison of unsigned expression in ‘>= 0’ is always true 

**-Wunused-but-set-variable**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:513
	variable ‘mr’ set but not used 

**-Wunused-function**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:177
	‘Dyninst::InstructionAPI::Expression::Ptr Dyninst::InstructionAPI::conditionalAssignment(unsigned int, Dyninst::InstructionAPI::Expression::Ptr, Dyninst::InstructionAPI::Result_Type)’ defined but not used 

**-Wunused-parameter**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:138
	unused parameter ‘immLen’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:157
	unused parameter ‘entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:162
	unused parameter ‘insn_to_complete’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:551
	unused parameter ‘insn_to_complete’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:571
	unused parameter ‘base’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:571
	unused parameter ‘offset’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:571
	unused parameter ‘m0’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:67
	unused parameter ‘i’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:86
	unused parameter ‘context’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:86
	unused parameter ‘type’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:87
	unused parameter ‘knownTargets’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:107
	unused parameter ‘bit’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:107
	unused parameter ‘ret_addr’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:107
	unused parameter ‘func’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:112
	unused parameter ‘retAddr’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:117
	unused parameter ‘context’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:117
	unused parameter ‘currBlk’ 

**-Wunused-variable**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:210
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:321
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:405
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:417
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:454
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:469
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:488
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:498
	unused variable ‘insn_entry’

### PR DESCRIPTION
**Pull request by bbiiggppiigg**
This commit should fix most of the compile warnings mentioned in #952  except -Wunused-parameter

The fix involves:
Reorder the C++ initializer list to get rid off reorder warnings
Removing unused functions copied from InstructionDecoer-aarch64.C
Unused variable commented out in amdgpu_vega_impl.C
Add cases to handle the yet-to-be-supported Arch_amdgpu_rdna in dyn_regs.C

Fixes #952

### CODE REVIEW

File: common/src/dyn_regs.C [hunk 1]
```diff
@@ -153,38 +153,44 @@ std::string MachRegister::name() const {
...
     std::string ret;
     if (iter != names()->end()) {
-        signed int arch = reg & 0xff000000;
-        if ( arch == Arch_amdgpu_vega){
+        if ( getArchitecture() == Arch_amdgpu_vega){
             signed int category = reg & 0x00ff0000;
             signed int base_val = reg & 0x000000ff;
             switch(category){
                 case amdgpu_vega::SGPR_VEC2:
+                    base_val -=  (amdgpu_vega::sgpr_vec2_0&0xff);
```
Comment (hainest) [inline common/src/dyn_regs.C:161]: Did you mean to include these `base_val` calculation changes?

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C [hunk 2]
```diff
@@ -137,7 +138,7 @@ namespace Dyninst {
 		void InstructionDecoder_amdgpu_vega::makeBranchTarget(bool branchIsCall, bool bIsConditional, int immVal,
 				int immLen = 16) {
 			Expression::Ptr lhs = makeAddExpression(makePCExpr(),Immediate::makeImmediate(Result(s48,4)),s48);
-			int64_t offset = sign_extend64(16, immVal * 4);
+			int64_t offset = sign_extend64(immLen, immVal * 4);
```
Comment (hainest) [inline instructionAPI/src/InstructionDecoder-amdgpu-vega.C:141]: Could we move this change to its own PR? It's a good change, but not in the scope of the compiler warning fixes.

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C [hunk 3]
```diff
@@ -154,15 +155,10 @@ namespace Dyninst {
...
-		bool InstructionDecoder_amdgpu_vega::pre_process_checks(const amdgpu_insn_entry &entry) {
-			bool ret = false;
-			return ret;
-		}
 
 		bool InstructionDecoder_amdgpu_vega::decodeOperands(const Instruction *insn_to_complete) {
 			assert(0 && "decodeOperands deprecated for amdgpu");
-
-			return true;
+			return insn_to_complete != NULL;
```
Comment (hainest) [inline instructionAPI/src/InstructionDecoder-amdgpu-vega.C:161]: Same as above.

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C [hunk 4]
```diff
@@ -318,7 +309,7 @@ namespace Dyninst {
 
 		void InstructionDecoder_amdgpu_vega::finalizeMTBUFOperands(){
 			layout_mtbuf & layout = insn_layout.mtbuf;
-			const amdgpu_insn_entry  &insn_entry = amdgpu_insn_entry::mtbuf_insn_table[layout.op];
+			//const amdgpu_insn_entry  &insn_entry = amdgpu_insn_entry::mtbuf_insn_table[layout.op];
```
Comment (hainest) [inline instructionAPI/src/InstructionDecoder-amdgpu-vega.C:312]: If we don't need these variables, let's remove them completely.

**Review by hainest — CHANGES_REQUESTED** [review]
I think these changes might be based on a branch that has changes that aren't in master. I just want to verify that some of the extra changes here were intentional.

We missed one switch case:

	dyninst/src/parseAPI/src/SymbolicExpression.C:369
		enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

The unused parameter warnings look like they could be cleaned up by just removing the variable name from the parameter. For example,

    bool IA_amdgpu::isFrameSetupInsn(Instruction i) const

would become

    bool IA_amdgpu::isFrameSetupInsn(Instruction) const

It's a non-semantic change, but it will make the compiler stop complaining.

File: common/src/dyn_regs.C (hunk 1 above)
Comment (bbiiggppiigg) [reply common/src/dyn_regs.C:161]: I thought these changes are included in the #948 , which is a pull request from the same branch as for this pull request,

https://github.com/dyninst/dyninst/pull/948/files/53a12aaeab008e36dd9a029229a2d0d599345d4b#diff-b7d9323c9547d36fd98664d3f98917e11290daaacbef0742396b393df003e52d

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C (hunk 2 above)
Comment (bbiiggppiigg) [reply instructionAPI/src/InstructionDecoder-amdgpu-vega.C:141]: It was complaining about the non-used function parameter immLen, which made me realize that this why I included immLen in the first place. I'll revert the change and remove the parameter name.

File: common/src/dyn_regs.C (hunk 1 above)
Comment (hainest) [reply common/src/dyn_regs.C:161]: Ah, you'll need to rebase this branch onto the head of master. The pull requests generate separate commit IDs, so github thinks yours is a different branch.

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C (hunk 2 above)
Comment (hainest) [reply instructionAPI/src/InstructionDecoder-amdgpu-vega.C:141]: Oh, I see. Let's use the passed parameter as you fixed it.

File: common/src/dyn_regs.C (hunk 1 above)
Comment (bbiiggppiigg) [reply common/src/dyn_regs.C]: Fetched and Force pushed, so this should have been resolved.

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C (hunk 2 above)
Comment (bbiiggppiigg) [reply instructionAPI/src/InstructionDecoder-amdgpu-vega.C:141]: This change is kept.

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C (hunk 3 above)
Comment (bbiiggppiigg) [reply instructionAPI/src/InstructionDecoder-amdgpu-vega.C]: Revert back to return true, and the parameter name is removed.

File: instructionAPI/src/InstructionDecoder-amdgpu-vega.C (hunk 4 above)
Comment (bbiiggppiigg) [reply instructionAPI/src/InstructionDecoder-amdgpu-vega.C]: These variables are removed.

**Comment by bbiiggppiigg** [comment]
@hainest I think the issues that you've mentioned should have been resolved by these commits.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR954

All the warnings are gone and the tests are unaffected. Thanks for getting this cleared up so quickly!
