### PR TITLE
Fix PowerPC branch instruction semantics

### LINKED ISSUE #1072: jump table analysis fails checking bclr opcode for ppcle so
For the dyninst ppcle target, jump table analysis during code parsing fails with:
Dyninst::DataflowAPI::RoseInsnPPCFactory::handleSpecialCases(entryID, SgAsmInstruction*, SgAsmOperandList*): Assertion `power_op_bclr == iapi_opcode' failed.

This patch bypasses the problem:
--- dyninst-11.0.0/dataflowAPI/src/RoseInsnFactory.C.orig	2021-06-09 15:54:21.753883619 -0400
+++ dyninst-11.0.0/dataflowAPI/src/RoseInsnFactory.C	2021-06-23 14:17:37.854933719 -0400
@@ -317,5 +317,5 @@
     // It looks like the ROSE semantics code will infer the target from 
     // the bo field. So, what is passed in as the third operands does not matter
-    if(branch_target) {
+    if(branch_target || iapi_opcode == power_op_bc) {
       rose_operands->append_operand(new SgAsmDoubleWordValueExpression(branch_target));
     } else if(power_op_bcctr == iapi_opcode) {

The problem is dependent on how libdw is built
 https://scox.fedorapeople.org/dyninst/libdw-0.185.ppc64le.so

### PR DESCRIPTION
**Pull request by hainest**
This should have been part of 64499aa304.

Fixes #1072

### CODE REVIEW

**Review by bbiiggppiigg — APPROVED** [review]

File: instructionAPI/src/InstructionDecoder-power.C [hunk 1]
```diff
@@ -305,7 +305,13 @@ which are both 0).
       auto target = makeRegisterExpression(ppc32::lr);
       insn_in_progress->addSuccessor(std::move(target), false, true, bcIsConditional, false);
 
-      if(bcIsConditional) {
+      bool const is_subroutine_return = [this]() {
```
[the remark this answers is not in the document]
Comment (hainest) [reply instructionAPI/src/InstructionDecoder-power.C:308]: I prefer self-documenting code when I can. Also, I made a couple of mistakes when I did the short version, so it was better for me, as well.

File: instructionAPI/src/InstructionDecoder-power.C [hunk 2]
```diff
@@ -302,11 +302,29 @@ which are both 0).
...
+      }();
+
+      bool const is_conditional = !is_subroutine_return;
+
+      {
+        auto target = makeRegisterExpression(ppc32::lr);
+        constexpr bool is_call = false;
+        constexpr bool is_indirect = true;
+        constexpr bool is_fallthrough = false;
+        insn_in_progress->addSuccessor(std::move(target), is_call, is_indirect, is_conditional,
```
Comment (kupsch) [inline instructionAPI/src/InstructionDecoder-power.C:317]: Is `std::move` useful in this case?

**Review by kupsch — APPROVED** [review]

File: instructionAPI/src/InstructionDecoder-power.C (hunk 2 above)
Comment (hainest) [reply instructionAPI/src/InstructionDecoder-power.C:317]: Strictly, it's a micro-optimization, but it saves a single ref update in the shared_ptr.

File: instructionAPI/src/InstructionDecoder-power.C [hunk 3]
```diff
@@ -294,28 +294,159 @@ which are both 0).
...
+          constexpr bool is_fallthrough = false;
+          insn_in_progress->addSuccessor(lr, is_call, is_indirect, is_conditional, is_fallthrough);
+        }
+      }
 
       if(bcIsConditional) {
-        insn_in_progress->addSuccessor(makeFallThroughExpr(), false, false, false, true);
+        auto target = makeFallThroughExpr();
+        constexpr bool is_call = false;
+        constexpr bool is_indirect = true;
```
Comment (bbiiggppiigg) [inline instructionAPI/src/InstructionDecoder-power.C:365]: I assume fallthrough should be indirect as in the original code?

File: parseAPI/src/IA_power.C [hunk 4]
```diff
@@ -316,12 +316,18 @@ bool IA_power::isReturn(Dyninst::ParseAPI::Function * context, Dyninst::ParseAPI
...
-  parsing_printf
-    ("isblrReturn at 0x%lx Addr 0x%lx 0x%lx Function addr 0x%lx leaf %d \n",
-     current, getAddr (), currBlk->start (), context->addr (),
-     func->_is_leaf_function);
-  if (!func->_is_leaf_function)
+
+  parsing_printf("Checking return idioms for %s@0x%lx in block=0x%lx, context=0x%lx\n",
+                 context->name().c_str(), getAddr(), currBlk->start(), context->addr());
+
+  if(func->_is_leaf_function) {
```
Comment (bbiiggppiigg) [inline parseAPI/src/IA_power.C:325]: You added a check for the case of leaf function and return early, but it seems like you didnt remove the original code in the else clause of if(_is_leaf_function) that does the same thing?

And maybe we should stick to just one of func or context for consistency (even though they seem to have the same value as func is assigned in line 319).

File: instructionAPI/src/InstructionDecoder-power.C [hunk 5]
```diff
@@ -1165,23 +1296,31 @@ which are both 0).
...
+
     if(!(field<6, 6>(insn))) {
       invertBranchCondition = !field<7, 7>(insn);
       if(insn_in_progress->getOperation().mnemonic == "bc") {
         insn_in_progress->getOperation().mnemonic = "b";
       }
       insn_in_progress->appendOperand(makeBIExpr(), true, false);
     }
-    if(field<8, 8>(insn) && field<6, 6>(insn)) {
+    if(writes_ctr && field<6, 6>(insn)) {
```
Comment (bbiiggppiigg) [inline instructionAPI/src/InstructionDecoder-power.C:1323]: writes_ctr checks for field<8,8>(insn) ==0, so here it should be (!writes_ctr) I assume?

File: instructionAPI/src/InstructionDecoder-power.C (hunk 3 above)
Comment (hainest) [reply instructionAPI/src/InstructionDecoder-power.C:365]: It's unclear what "indirect" means here. Except for printing, Dyninst only uses that information in only one place: https://github.com/dyninst/dyninst/blob/v13.0.0/dyninstAPI/src/Relocation/Widgets/CFWidget.C#L150. 

The comment there is

```
   // Indirect branch:
   //   1) Just go for it... we have no control, really
```

Super helpful. Given this, I interpret an "indirect" control flow target to be contained in some location that must be dereferenced before being used (e.g., branching through a register) as opposed to being a literal offset or absolute target. Hence, fallthrough targets are always indirect since they go through the PC (or the LR for ppc).

File: parseAPI/src/IA_power.C (hunk 4 above)
Comment (hainest) [reply parseAPI/src/IA_power.C:325]: This is still a draft, so that code is actually going away. I wish GitHub would let you remove a review request, but it won't. Sorry.

File: instructionAPI/src/InstructionDecoder-power.C (hunk 3 above)
Comment (bbiiggppiigg) [reply instructionAPI/src/InstructionDecoder-power.C:365]: I thiink fallthrough targets are always direct snice they are literally the next instruction and does not need to go through the process of resolving indirect jump target.

Comment (hainest) [reply instructionAPI/src/InstructionDecoder-power.C:365]: My biggest problem is that `InstructionDecoder_power::makeFallThroughExpr` assumes that the fallthrough target can be addressed via the PC, but Power doesn't have one[1]. Since it's not direct, then I considered it indirect. But a re-read of the decode algorithms for conditional branch instructions doesn't actually indicate that. I'll change this back to being direct to make it consistent with the other architectures. As an aside, I plan to change the  CFT interface when updating to Capstone to make all of this more explicit.

[1] From the docs:
```
Obtaining the address of the next instruction:
Use the following form of Branch and Link.

    bcl 20,31,$+4
```
where `$` is an assembler directive.

**Comment by hainest** [comment]
With https://github.com/dyninst/testsuite/pull/256, this reduces the failures from ~99% to <1%.

File: parseAPI/src/IA_power.C [hunk 6]
```diff
@@ -309,91 +309,9 @@ bool IA_power::isReturnAddrSave(Address& retAddr) const
   return ret;
 }
 
-bool IA_power::isReturn(Dyninst::ParseAPI::Function * context, Dyninst::ParseAPI::Block* currBlk) const
+bool IA_power::isReturn(Dyninst::ParseAPI::Function *, Dyninst::ParseAPI::Block*) const
 {
-  /* Check for leaf node or lw - mflr - blr pattern */
```
Comment (bbiiggppiigg) [inline parseAPI/src/IA_power.C:314]: Is this pattern no longer being used in powerpc so we don't need to check it anymore?

Comment (hainest) [reply parseAPI/src/IA_power.C:314]: Correct. This is from ancient POWER and hasn't been used since v2.0 (~Power7) which is the oldest we support.

File: instructionAPI/src/InstructionDecoder-power.C [hunk 7]
```diff
@@ -294,28 +294,158 @@ which are both 0).
...
+        bool const is_written = (LK == 1);
+        insn_in_progress->appendOperand(link_register, is_read, is_written, is_implicit);
+      };
+
+      if(LK == 1) {
+        // Case 3 - Function call
+        auto ctr = makeRegisterExpression(ppc32::ctr);
+        constexpr bool is_indirect = true;
+        constexpr bool is_call = true;
+        bool const is_fallthrough = false;
```
Comment (bbiiggppiigg) [inline instructionAPI/src/InstructionDecoder-power.C:417]: Any reason why this is not constexpr like the others?
And just a thought, would it be more clear if we define is_indirect/is_call/is_fallthrough/is_conditoinal all as true the start of the function, and then do something like appendOperand(..., is_call, is_indirect, !is_conditiona, !is_fallthrough);

Comment (hainest) [reply instructionAPI/src/InstructionDecoder-power.C:417]: > Any reason why this is not constexpr like the others?

Nope, that was just a mistake.

> And just a thought, would it be more clear if we define is_indirect/is_call/is_fallthrough/is_conditoinal all as true the start of the function, and then do something like appendOperand(..., is_call, is_indirect, !is_conditiona, !is_fallthrough);

Good idea! I should do that since I did that in the tests.

Comment (hainest) [reply instructionAPI/src/InstructionDecoder-power.C]: Updated.

**Comment by kupsch** [comment]
@hainest I see the same test suite problem of it not running most of the tests.  18 tests run and PASS and then it stops.  It looks like ptrace is being restricted due to an update or a CSL configuration change. I found this in `stderr.log`:

```
Warning: your Linux system provides limited ptrace functionality as a security
measure. This measure prevents ProcControl and Dyninst from attaching to binaries.
To temporarily disable this measure (until a reboot), execute the following command:
        echo 0 > /proc/sys/kernel/yama/ptrace_scope
To permanently disable this measure, edit the file "/etc/sysctl.d/10-ptrace.conf"
and follow the directions in that file.
For more information, see https://wiki.ubuntu.com/SecurityTeam/Roadmap/KernelHardening
```

I'll open an issue with the CSL.

**Comment by hainest** [comment]
Thanks for the feedback, all.

@kupsch I just tried to run the test suite on follis, but it still failed early. I'm going to go ahead and merge this since I've not seen any regressions on the other x86 machines.

**Comment by kupsch** [comment]
@hainest, I too only see 18 tests run and PASSed. The ptrace setting was made, and I can attach to another process with gdb `gdb -p ...` so the setting seems to be active.  The ptrace failure message is no longer present in the testsuite logs, so something else must be going wrong.

**Comment by hainest** [comment]
@kupsch Have you tried running without this commit?

**Comment by kupsch** [comment]
WIth the previous commit (fb151...), 18 run with 2 failures (power_cft and power_decode).  I'll try going back further.

**Comment by kupsch** [comment]
@hainest I tried instances of dyninst and the testsuite from many months ago, where there were 1552 PASSED tests and 0 FAILED on x86, and I still see 18 PASSED and 0 FAILED. I'll investigate further next week.
