### PR TITLE
fix building of symlite

### LINKED ISSUE #1171: SymLite won't compile
This will fix the CMake problem:

    diff --git a/CMakeLists.txt b/CMakeLists.txt
    index 994d3e35b..32670fded 100644
    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -143,7 +143,9 @@ if(BUILD_RTLIB)
         if(TARGET TBB)
           add_dependencies(DyninstRT TBB)
         endif()
    -    add_dependencies(dyninstAPI DyninstRT)
    +    if(TARGET dyninstAPI)
    +      add_dependencies(dyninstAPI DyninstRT)
    +    endif()
         if(TARGET dyninstAPI-static)
           add_dependencies(dyninstAPI-static DyninstRT)
         endif()

---

The `InstructionSource` interface has changed, and `SymReaderCodeRegion` needs to be updated to not be an abstract class.

    /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/src/SymLiteCodeSource.C: In member function ‘void Dyninst::ParseAPI::SymReaderCodeSource::init_regions()’:
    /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/src/SymLiteCodeSource.C:233:60: error: invalid new-expression of abstract class type ‘Dyninst::ParseAPI::SymReaderCodeRegion’
      233 |       CodeRegion* cr = new SymReaderCodeRegion(_symtab, tmp);
          |                                                            ^
    In file included from /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/src/SymLiteCodeSource.C:41:
    /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/h/SymLiteCodeSource.h:51:7: note:   because the following virtual functions are pure within ‘Dyninst::ParseAPI::SymReaderCodeRegion’:
       51 | class SymReaderCodeRegion : public CodeRegion {
          |       ^~~~~~~~~~~~~~~~~~~
    In file included from /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/h/CodeSource.h:42,
                     from /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/h/SymLiteCodeSource.h:39,
                     from /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/src/SymLiteCodeSource.C:41:
    /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/h/InstructionSource.h:52:18: note:     ‘virtual bool Dyninst::InstructionSource::isReadOnly(Dyninst::Address) const’
       52 |     virtual bool isReadOnly(const Address) const = 0;
          |                  ^~~~~~~~~~
    /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/src/SymLiteCodeSource.C: In member function ‘void Dyninst::ParseAPI::SymReaderCodeSource::overlapping_warn(const char*, unsigned int) const’:
    /home/tim/paradyn/E1DwJqF1/dyninst/src/parseAPI/src/SymLiteCodeSource.C:403:54: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
      403 |         fprintf(stderr,"Invocation of routine at %s:%d is ambiguous for "
          |                                                     ~^
          |                                                      |
          |                                                      int
          |                                                     %d
      404 |                        "binaries with overlapping code regions\n",
      405 |             file,line);
          |                  ~~~~                                 
          |                  |
          |                  unsigned int
    make[2]: *** [parseAPI/CMakeFiles/parseAPI.dir/build.make:1031: parseAPI/CMakeFiles/parseAPI.dir/src/SymLiteCodeSource.C.o] Error 1

I don't have time to fix this before I go out of town. @kupsch @bigtrak Could one of you take a look? @wcohen needs this for some work he is doing (see https://github.com/dyninst/dyninst/issues/1168).

### PR DESCRIPTION
**Pull request by kupsch**
Allow Dynist to build if configured with -DLIGHTWEIGHT_SYMTAB (symlite):
- add missing pure virtual functions isReadOnly
- fix isCode and isData methods to use program header permissions instead
  of just returning true
- fix printf compiler warning
- disable parseThat if using symlite as it is not compatible
- remove #include <linux/elf.h> from proccontrol/src/linux.h on aarch64
  if SYMLITE is configured as it is incompatible with <elf.h>

Fixes #1171

### CODE REVIEW

File: parseAPI/h/SymLiteCodeSource.h [hunk 1]
```diff
@@ -109,6 +110,7 @@ class SymReaderCodeSource : public CodeSource {
     PARSER_EXPORT unsigned int getAddressWidth() const;
     PARSER_EXPORT bool isCode(const Address) const;
     PARSER_EXPORT bool isData(const Address) const;
+    PARSER_EXPORT bool isReadOnly(const Address) const;
```
Comment (hainest) [inline parseAPI/h/SymLiteCodeSource.h:113]: Could you add `override` on these?

**Review by hainest — CHANGES_REQUESTED** [review]
