### PR TITLE
 Fix int size of rose operations return values

### LINKED ISSUE #1517: Rose logicalNot implemented as 1's complement
**Describe the bug**

https://github.com/dyninst/dyninst/blob/bec7e21a5008adc1c0445775602ce740943e9b55/dataflowAPI/rose/semantics/BaseSemantics2.h#L1734-L1735

Currently, Rose didn't extinguish between logical and bitwise operation ( and / or / invert ).
And invert is used to implement logicalNot.

https://github.com/dyninst/dyninst/blob/bec7e21a5008adc1c0445775602ce740943e9b55/dataflowAPI/rose/semantics/BaseSemantics2.C#L243-L246

https://github.com/dyninst/dyninst/blob/bec7e21a5008adc1c0445775602ce740943e9b55/dataflowAPI/rose/semantics/BaseSemantics2.C#L225-L233

However, since we didn't limit its input to invert to 1 bit, inverting an non-zero value can still result in a non-zero value, causing incorrect result.

https://github.com/dyninst/dyninst/blob/bec7e21a5008adc1c0445775602ce740943e9b55/parseAPI/src/SymbolicExpression.C#L240-L245

https://github.com/dyninst/dyninst/blob/bec7e21a5008adc1c0445775602ce740943e9b55/parseAPI/src/SymbolicExpression.C#L271-L281

### PR DESCRIPTION
**Pull request by bbiiggppiigg**
- set integer bit size of equalsizeOp to be 1
- set integer bit size of andOp to be max size of operands
- set integer bit size of orOp to be max size of operands

Fix #1517

### CODE REVIEW

File: parseAPI/src/SymbolicExpression.C [hunk 1]
```diff
@@ -242,14 +242,20 @@ AST::Ptr SymbolicExpression::SimplifyRoot(AST::Ptr ast, Address addr, bool keepM
                                           if (roseAST->child(0)->getID() == AST::V_ConstantAST && roseAST->child(1)->getID() == AST::V_ConstantAST) {
                                               ConstantAST::Ptr child0 = boost::static_pointer_cast<ConstantAST>(roseAST->child(0));
                                               ConstantAST::Ptr child1 = boost::static_pointer_cast<ConstantAST>(roseAST->child(1));
-                                              return ConstantAST::create(Constant(child0->val().val & child1->val().val, 64));
+                                              auto size0{child0->val().size};
+                                              auto size1{child1->val().size};
+                                              uint64_t newSize{size0 > size1 ? size0 : size1};
```
Comment (kupsch) [inline parseAPI/src/SymbolicExpression.C:247]: use std::max

File: parseAPI/src/SymbolicExpression.C [hunk 2]
```diff
@@ -242,14 +242,20 @@ AST::Ptr SymbolicExpression::SimplifyRoot(AST::Ptr ast, Address addr, bool keepM
...
                                           }
                                           break;
             case ROSEOperation::orOp:
                                           if (roseAST->child(0)->getID() == AST::V_ConstantAST && roseAST->child(1)->getID() == AST::V_ConstantAST) {
                                               ConstantAST::Ptr child0 = boost::static_pointer_cast<ConstantAST>(roseAST->child(0));
                                               ConstantAST::Ptr child1 = boost::static_pointer_cast<ConstantAST>(roseAST->child(1));
-                                              return ConstantAST::create(Constant(child0->val().val | child1->val().val, 64));
+                                              auto size0{child0->val().size};
+                                              auto size1{child1->val().size};
+                                              uint64_t newSize{size0 > size1 ? size0 : size1};
```
Comment (kupsch) [inline parseAPI/src/SymbolicExpression.C:257]: use std::max

**Review by kupsch — APPROVED** [review]
Looks good, but make the following changes before merging (if you make just these changes I don't need to review again):

1) Use std::max instead writing your own

2) Change the title, commit title and commit body to be clearer

For the title omething like *Fix int size of rose operations return values*.

For the items, use a markdown list and make the change clearer:

```
- set integer bit size of equalsizeOp to be 1
- set integer bit size of andOp to be max size of operands
- set integer bit size of orOp to be max size of operands
```
