### PR TITLE
Correctly handle DWARF subroutines during parallel parsing

### LINKED ISSUE #1214: Dwarf parsing bug for function defined in multiple compilation units
**Intention**
Symtab's API to get function parameters and local variables should return the correct number and types

**Describe the bug**
If.a library or executable has a definition of a function in multiple compilation units within a single library or executable, then the parameters and local variables are duplicated for each occurrence.  This results in number, names and types of parameters being incorrect as the duplicates are interleaved in indeterminate order.  Also the function's local variables are duplicated.  One way that a function can be defined in more than one compilation is for templated classes/functions where the code is emitted in each object file and then the linker picks one copy and make the dwarf location in each function point to this one copy. 

**To Reproduce**
Open a library that uses templated C++ classes or functions and get the parameters for each function.  The symtabAPI library is an instance of this as it use iostreams and STL.

**Expected behavior**
Correct number of parameters and only one copy of local variables.

**System (please complete the following information):**
 - All platforms
 - Present since parallel dwarf parsing was added (10.2)

### PR DESCRIPTION
**Pull request by kupsch**
Fix to only process the DWARF for a function (subprogram) once if it is defined
in multiple compilation units within a library or executable.  This prevents
duplication of parameters, local variables and use of thread-unsafe data
structures from concurrent threads.

Fixes #1214

### CODE REVIEW

File: symtabAPI/src/dwarfWalker.h [hunk 1]
```diff
@@ -233,7 +237,9 @@ class DwarfWalker : public DwarfParseActions {
 
     } Error;
 
-    DwarfWalker(Symtab *symtab, Dwarf* dbg);
+    using ParsedFuncs = tbb::concurrent_hash_map<FunctionBase *, bool>;
```
Comment (hainest) [inline symtabAPI/src/dwarfWalker.h:240]: I know that the old implementation used a `std::set<FunctionBase*>`, but we have had a great many bugs tied to using pointers as keys in associative containers. Now would be a great time to excise this one. I _think_ the easiest solution is to make a hasher to capture the symbol name, address, and module name to make them unique.

File: symtabAPI/src/dwarfWalker.h [hunk 2]
```diff
@@ -400,8 +411,8 @@ class DwarfWalker : public DwarfParseActions {
             Dwarf_Sword listLength);
 
 
-    // Header-only functions get multiple parsed.
-    std::set<FunctionBase *> parsedFuncs;
+    // Map of Function* to bool (indicates function parsed)
+    std::shared_ptr<ParsedFuncs> parsedFuncs;
```
Comment (hainest) [inline symtabAPI/src/dwarfWalker.h:415]: This has to be a `boost::shared_ptr`. Sigh. Maybe one day we'll adopt a C++ standard that's not a decade old. Also, I'm assuming this is shared not because of ownership but for copy semantics (i.e., we don't want to make DwarfWalker move-only by using a unique_ptr here)?

**Review by hainest — CHANGES_REQUESTED** [review]

**Comment by hainest** [comment]
@kupsch @bigtrak Summit and Ray testing are OK.
